# Generated by Django 4.2.9 on 2024-02-04 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_category_tag_post_counted_view_post_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
