# Generated by Django 4.2.9 on 2024-02-10 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_post_category_post_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tag",
        ),
    ]
